[project]
name = "smc-toolkit"
version = "0.1.0"
description = "Smart Money Concepts (SMC) analysis toolkit for BOS, CHoCH, FVG, OB, and swing structure."
readme = "README.md"
authors = [
  { name = "Your Name", email = "your.email@example.com" }
]
license = { text = "MIT" }
keywords = ["trading", "smart-money", "bos", "choch", "fvg", "orderblock"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
requires-python = ">=3.7"
dependencies = [
  "pandas>=1.0",
  "numpy>=1.18",
  "matplotlib>=3.0"
]

[project.urls]
Homepage = "https://github.com/yourusername/smc-toolkit"
